name: 'Run benchmark'

on: # rebuild any PRs and main branch changes
  pull_request:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      # Create new file to simulate change and test it's committing/pushing
      - name: Create new file
        run: |
          echo "test" > test.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update performance results in README.md"
