name: 'Run benchmark'

on: # rebuild any PRs and main branch changes
  pull_request:

jobs:
  build:
    runs-on: benchmarking-runner
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: graphql-benchmarks
          push: never
          runCmd: |
            bash ./setup.sh
            bash ./run_benchmarks.sh

      - uses: actions/checkout@v4
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update performance results in README.md"
          branch: ${{ github.head_ref }}
